DataDog/datadog-lambda-go

ddlambda.go
internal/metrics/batcher.go
internal/metrics/batcher_test.go
internal/metrics/model.go
internal/metrics/processor.go
internal/metrics/processor_test.go

Changes distribution metrics so their timestamps are preserved instead of being aggregated.

Darcy rayner/fix metric timestamps

---

README.md
ddlambda.go
internal/metrics/api.go
internal/metrics/api_test.go
internal/metrics/constants.go
internal/metrics/listener.go

Makes the Datadog site configurable, so user's can swap between the european api endpoint, and the north american one.

Add Site configuration option

---

internal/trace/context.go
internal/trace/context_test.go

Fixes a bug where incorrect parentID is used when receiving datadog trace headers.
Old:
New:

Darcy.rayner/fix xray parents

---

internal/wrapper/wrap_handler.go
internal/wrapper/wrap_handler_test.go

Adds support for the lambda handler format:
```go
func handler(ctx context.Context) {}
```
We missed this one in our previous test cases.

Fix support for handler single argument context input

---

README.md
ddlambda.go
internal/metrics/constants.go
internal/metrics/context.go
internal/metrics/context_test.go
internal/metrics/listener.go
internal/metrics/listener_test.go
internal/metrics/processor.go

Adds DD_FLUSH_TO_LOG support, (log forwarding). Also, there is a refactor here that moves more logic from ddlambda.go to the metrics around creating metrics. This was to keep the logic around using the log forwarder simple and contained to the metrics package.

Darcy.rayner/log forwarding

---

internal/testdata/non-proxy-mixed-case-metadata.json
internal/trace/context.go
internal/trace/context_test.go

*Note: Please remember to review the [contribution guidelines](https://github.com/DataDog/datadog-lambda-go/blob/master/CONTRIBUTING.md)
if you have not yet done so.*
Supports incoming mixed case trace headers.
Some libraries/frameworks will force mixed casing when sending headers. We should support those.
How did you test this pull request?
Anything else we should know when reviewing?

Support mixed case trace headers

---

README.md
ddlambda.go
internal/metrics/listener.go
internal/metrics/listener_test.go

* Adds the ability to configure the timestamp sent with metrics
* Renames the `Distribution` function to `Metric`
From [this feature request](https://github.com/DataDog/datadog-lambda-go/issues/11)

Add option to specify timestamp of custom metric

---

ddlambda.go
ddlambda_test.go
internal/wrapper/wrap_handler.go

* Fixes nil pointer exception when calling "Metric" outside of wrapped context.
* Adds InvokeDryRun to make unit testing/local testing easier. Issue #22

Improve ability to run package code in tests

---

ddlambda.go
internal/metrics/listener.go
internal/metrics/listener_test.go
internal/wrapper/wrap_handler.go
internal/wrapper/wrap_handler_test.go

Adds the enhanced metrics of `aws.lambda.enhanced.invocations` and `aws.lambda.enhanced.errors` and the respective tags from the Lambda Context. This includes the custom tag of  `cold_start:true|false`.
Includes unit tests for proper grabbing of enhanced metric tags, and for submission of the metric to a host/site.

add enhanced metrics: invocations and errors

---

ddlambda.go
internal/logger/log.go
internal/metrics/listener.go
internal/metrics/listener_test.go

Modifies enhanced metrics to always be flushed to logs, when enabled.
Previously enhanced metrics were enabled by default, but they would send over http if the logs option was turned off.

Always send enhanced metrics through logs

---

internal/metrics/api.go

Set a ten second timeout on the `http.Client` used to communicate with the DataDog API.
The Go HTTP Client specifies no timeout by default, which means - theoretically - a request could hang indefinitely under unfortunate server conditions. This is especially unfortunate given this library is designed to run in Lambda, where execution time is money.
I chose 10 seconds somewhat arbitrarily. I'm open to other values, or even to making it tunable. My hope is that this PR will start a conversation, more than just being accepted. I have a poor understanding of what the Datadog API latency guarantees are around the globe.
I `go test`ed it. I also used it on a test lambda internally. It works exactly as expected under non-pathological cases.

Time out to DD API after 10 seconds

---

LICENSE
NOTICE
README.md
ddlambda.go
ddlambda_test.go
internal/metrics/api.go
internal/metrics/api_test.go
internal/metrics/batcher.go
internal/metrics/batcher_test.go
internal/metrics/constants.go
internal/metrics/context.go
internal/metrics/context_test.go
internal/metrics/kms_decrypter.go
internal/metrics/kms_decrypter_test.go
internal/metrics/listener.go
internal/metrics/listener_test.go
internal/metrics/model.go
internal/metrics/processor.go
internal/metrics/processor_test.go
internal/metrics/time.go
internal/trace/constants.go
internal/trace/context.go
internal/trace/context_test.go
internal/trace/listener.go
internal/trace/listener_test.go
internal/wrapper/wrap_handler.go
internal/wrapper/wrap_handler_test.go

When decrypting the API key using KMS, try first with the encryption context added by the Lambda console UI, then try without.
The Lambda console UI changed the way it encrypts environment variables. The current behavior is to encrypt environment variables using the function name as an encryption context. Previously, the behavior was to encrypt environment variables without an encryption context. The Lambda Extension currently only supports API keys encrypted using the previous behavior. We need to support both, as supplying the incorrect encryption context will cause decryption to fail.
I added unit test coverage for this function and tested manually.

Support decrypting API keys encrypted with an encryption context

---

internal/trace/listener.go
internal/trace/listener_test.go

This pr changes the behavior of the `separateVersionFromFunctionArn` to check the capacity of the arnSegments slice before reslicing to avoid panics in case the slice capacity is not at least 7.
I was debugging a lambda function locally, so the LambdaContext object had an empty `InvokedFunctionArn` field. This caused the `separateVersionFromFunctionArn` to panic when reslicing `[0:7]` since the slice has capacity less than 7. As a result, my handler was never called.
I added a unit test. I also ran my code against this fork to verify the fix works. It works.

Change separateVersionFromFunctionArn function to check slice capacity before slicing

---

internal/metrics/kms_decrypter.go
internal/metrics/kms_decrypter_test.go

When the API key is encrypted using the AWS console, the function name is added as an encryption context. When the API key is encrypted using the AWS CLI, no encryption context is added. We need to try decrypting the API key both with and without the encryption context, because decrypting using the incorrect encryption context will cause decryption to fail. 
Previously, we tried decrypting WITH the encryption context first, then fell back to encrypting WITHOUT the encryption context. This PR reverses the order and tries decrypting WITHOUT the encryption context first, falling back to encrypting WITH the encryption context.
We want to encourage customers to encrypt their keys using the AWS CLI, without the encryption context. That way, a single encrypted key can be re-used for multiple …

Try encrypting KMS key without encryption context first

---

ddlambda.go
internal/wrapper/wrap_handler.go
internal/wrapper/wrap_handler_test.go

Adds support for lambda.StartHandler, via a new method WrapHandlerInterface
#72 
The new code is covered by unit tests.

Add WrapHandlerInterface to support lambda.StartHandler

---

internal/testdata/non-proxy-with-missing-sampling-priority.json
internal/trace/context.go
internal/trace/context_test.go

Fixes #74. If datadog-lambda-go comes across a trace that does not have sampling-priority set, it should set a default priority (I think Tian decided on sampler-keep, but I will confirm.) This matches the behavior of other datadog-lambda-* libraries.

Set default sampling priority to sampler-keep

---

internal/trace/listener.go
internal/trace/listener_test.go

Add the `functionname` attribute to the Lambda span metadata. 
Look at problem 2 here: https://docs.google.com/document/d/1Jd40XCKibvhVntIiT02xjaZZlq3P2ohRHZ8VnKtu46Q/edit#
Check the trace metadata tags to ensure the `functionname` attribute is present.

[SLS-1260] Add functionname attribute to span metadata

---

ddlambda.go
internal/metrics/listener.go

When the Datadog Lambda Extension is running, do not show error messages even if neither `DD_API_KEY` nor `DD_KMS_API_KEY` is set.
In #101, it became clear that when the Datadog Lambda Extension is running, this library does not require either `DD_API_KEY` or `DD_KMS_API_KEY`.
Therefore, when the Extension is running, even if neither `DD_API_KEY` nor `DD_KMS_API_KEY` is set, error messages should not appear.
Same as #101. No error messages were shown even though neither `DD_API_KEY` nor `DD_KMS_API_KEY` was set 👍

Do not show error messages even if neither `DD_API_KEY` nor `DD_KMS_API_KEY` is set when Lambda Extension is running

---

README.md

Consolidate serverless configurations into one place https://docs-staging.datadoghq.com/tian.chu/serverless-configuration/serverless/configuration.

Consolidate serverless configurations into one place

---

ddlambda.go
internal/extension/extension.go
internal/extension/extension_test.go
internal/trace/listener.go
internal/trace/listener_test.go
internal/wrapper/wrap_handler.go

Extends the DD extension functionality in the Go Lambda library to support universal instrumentation. In short, this means that the extension will handle certain features such as adding function triggers, Lambda request and response to the span metadata and inferred spans.
Gated behind the `DD_UNIVERSAL_INSTRUMENTATION` env var.
Expand universal instrumentation to all runtimes. 
Manually with dev builds of the library

[SLS-2330] Add support for universal instrumentation with the extension

---

tests/integration_tests/run_integration_tests.sh

Explicitly set the architecture to be able to run integration testing on M1

run integration tests locally on M1

---

tests/integration_tests/run_integration_tests.sh
tests/integration_tests/snapshots/logs/error.log
tests/integration_tests/snapshots/logs/hello.log

mask the new init runtime log + update snapshots

mask init runtime logs

---

internal/extension/extension.go
internal/extension/extension_test.go
internal/trace/context.go
internal/trace/context_test.go
internal/trace/listener.go
internal/trace/listener_test.go

When this lambda function is a consumer for a SQS queue, collect the trace context passed back from the extension and apply it.
Traces with a go SQS consumer were broken.
Sample trace using these updates
Note that any child span created inside the lambda function currently will not appear in the trace. This is because the extension isn't reading sampling priority and therefore the tracer defaults to priority 0 (throw it away). See https://datadoghq.atlassian.net/browse/SVLS-3537.
For some reason I am not seeing the `aws.lambda` span created for my sqs consumer. This should be created in the extension when universal instrumentation is turned on. I haven't been able to get to the bottom of this. However, I have been able to show that any child spans created in the SQS comsumer lambda will …

Propagate trace context from SQS events

---

awslambdanorpc.go
awslambdawithrpc.go
ddlambda.go
internal/logger/log.go

In order to simplify onboarding & make it more uniform across languages, inspect the value of the `DD_SERVERLESS_APPSEC_ENABLED` environment variable, and overrides `AWS_LAMBDA_RUNTIME_API` to redirect the Lambda runtime API to the Datadog extension so that the AppSec proxy is used, and turns on `DD_UNIVERSAL_INSTRUMENTATION` (unless it was already manually configured by the user).
This is necessary/useful because the `AWS_LAMBDA_EXEC_WRAPPER` environment variable is not honored by custom runtimes (`provided`, `provided.al2`) as well as the `go1.x` runtime (which is a glorified provided runtime). The datadog Lambda wrapper starts a proxy to inject ASM functionality directly on the Lambda runtime API instead of having to manually instrument each and every lambda handler/application, and …

feat: automate AppSec enablement setup (e.g: `AWS_LAMBDA_RUNTIME_API`)

---

ddlambda.go
ddlambda_test.go

Enabled universal instrumentation and tracing by default.
Honors environment variable if set.
Multiple tickets of customers not understanding why they need to have another env var to get inferred spans ready.
- Updated unit tests to respect previous behavior: tracing and universal instrumentation disabled.

feat: enable universal instrumentation by default

---

ddlambda.go
ddlambda_test.go
internal/metrics/listener.go
internal/metrics/listener_test.go

Only calls `Flush()` on the extension when running in local test mode.
See https://github.com/DataDog/datadog-lambda-python/pull/406
This cuts runtime duration of a hello world function by about 10%.

Do not call flush extension after each invocation.

---

internal/trace/listener.go

Today, if `DD_SERVICE` is used, the service name is still set to `aws.lambda`.
This PR removes that logic, and uses the defaults of the Go tracer (so defaulting to the binary name).
Behavior before:
Traces have a service name `aws.lambda` is `DD_SERVICE` isn't set
Data streams have a service `aws.lambda` if `DD_SERVICE` isn't set
If DD_SERVICE is set, only APM picks it up.
Behavior after:
Same if DD_SERVICE isn't set
If DD_SERVICE is set, both APM service name & DSM service name use it.

internal/trace/listener: Don't override service name

---

internal/extension/extension.go

This sends the error message along with an error flag 
When running with universal instrumentation on were loosing error messages if lambdas are returning errors, which impacts our ability to debug issues:
With this addition the error message is retained:
Sabotaged a lambda behind API gateway to reproduce the issue reliably, and then cloned the code, used a replace directive to import the local patched version, deployed and repeated the test (see the attached screenshot). There weren't any unit tests with coverage on the existing case so I did not add any unit testing.

Send error message along with error flag

---

ddlambda.go
internal/extension/extension.go
internal/extension/extension_test.go
internal/trace/listener.go

From https://github.com/DataDog/datadog-lambda-go/pull/170 but adds tests.

Set error type and stack with universal instrumentation

---

ddlambda.go
internal/trace/listener.go

Adding a possibility to extend the tracer options.
We'd like to be able to extend the tracer with a couple of custom options.

Add possibility to extend tracer options

---

internal/extension/extension.go
internal/extension/extension_test.go

Fixes sampling rates not being respected.
When a sampling priority is set on a span but not in the context, we should still propagate it to the Lambda extension. Previously the sampling priority was not being sent to the extension in this case, causing sampling rates to be incorrect.
Sampling rates didn't work before, leading to 100% of traces being sampled regardless of the `DD_TRACE_SAMPLING_RULES` or `DD_TRACE_SAMPLE_RATE` environment variables.
Manual testing. Before changes, we saw every trace was being sampled. Now, we see the correct number of traces being sampled depending on the sample rate environment variable.
I also added unit tests in `extension_test.go`.

Fix sampling rate

---

ddlambda.go
ddlambda_test.go
internal/metrics/kms_decrypter.go
internal/metrics/listener.go
internal/metrics/listener_test.go

Correctly handles the `DD_LAMBDA_FIPS_MODE` control, same as we do in the python and js layers.
We no longer support direct Datadog API metric submission when `DD_LAMBDA_FIPS_MODE` is enabled. This setting is enabled by default in govcloud. Various mechanisms are provided to override this configuration value.
Please note that we did not previously actually send metrics with timestamps to the extension. Metrics with timestamps get turned into metrics with timestamp=now. This is still the behavior after this change.
Added some unit tests. Will also deploy to self-monitoring.

feat: DD_LAMBDA_FIPS_MODE handling for metrics

---

ddlambda.go

Fix comment for OTEL env var reading condition.
While reading the code to check the configuration values of datadog-lambda-go, I noticed that the comment and the implementation are incorrect.
Code reading (because this PR only changes the comment).
When reading the `HandlerStarted` function, I noticed that if `l.ddTraceEnabled` is false, the function returns early, while if it is true, the process continues and further actions are taken depending on the condition of `l.otelTracerEnabled`. In other words, when Datadog Trace is enabled, OpenTelemetry Trace is also enabled. This shows that the comment is incorrect and the implementation is correct. 
The comment was inserted by:
- https://github.com/DataDog/datadog-lambda-go/pull/159

Fix comment for OTEL env var reading condition

---

internal/trace/listener.go

Reverts the addition of `tracer.Stop` to the end of each invocation.
Nightly e2e tests are failing. We are seeing no golang traces at all, except when `cold_start=true`.

Revert calling tracer.Stop after each invocation.
